export enum BURGER_CONSTRUCTOR_ACTIONS_TYPE {
  ADD_INGREDIENT = 'ADD_INGREDIENT',
  REMOVE_INGREDIENT = 'REMOVE_INGREDIENT',
  CLEAR_CONSTRUCTOR = 'CLEAR_CONSTRUCTOR',
  SORT_INGREDIENTS = 'SORT_INGREDIENTS',
}
